# Values tailored for Istio gateway Service to expose NodePort 30080
global:
  hub: docker.io/istio
  tag: "1.22.0"

# Configure the built-in ingress gateway to expose nodePort 30080
ingressGateways:
  - name: istio-ingressgateway
    enabled: true
    label:
      istio: ingressgateway
    k8s:
      service:
        type: NodePort
        ports:
          - port: 80
            name: http2
            targetPort: 8080
            nodePort: 30080
          - port: 443
            name: https
            targetPort: 8443
            nodePort: 30443
