apiVersion: v1
kind: Secret
metadata:
    name: {{ include "my-app.fullname" . }}
    labels:
        app: {{ include "my-app.fullname" . }}
        name: {{ include "my-app.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ tpl $val $ | b64enc }}
  {{- end}}
