apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: app-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 30080
        name: http-30080
        protocol: HTTP
      hosts:
        - "api.app.com"
