replicaCount: 2
namespace: dev
name: my-app

image:
  repository: my-app
  tag: ""
  pullPolicy: Never

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

service:
  namespace: dev
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: my-service
