Deployment:
replicaCount: 2
namespace: dev
name: my-app
image:
  repository: python
  tag: "latest"
  pullPolicy: IfNotPresent
autoscaling:
  enabled: false

serviceAccount:
 create: false
 name: ""

service:
  namespace: dev
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: my-service
